version: '3.7'
services:
  # In theory you can have multiple controllers as long as they share the db
  # this is not tested
  controller1:
    container_name: currency-controller1
    hostname: controller1
    image: github.com/hongkongkiwi/go-currency-nodes/controller
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - "APP_NAME=controller"
    ports:
      - 127.0.0.1:5060:5060
    expose:
      - 5060
    volumes:
      # Persistant subscription and price data
      - "./docker/instancedata/controller/db:/db:rw"
    environment:
      - "CONTROLLER_LISTEN_ADDR=0.0.0.0:5060"
      - "CONTROLLER_DB_DIR=/db"
      - "CONTROLLER_CURRENCY_PAIRS=USD_HKD,HKD_USD,USD_NZD,NZD_USD,BTC_HKD,HKD_BTC,BTC_USD,USD_BTC"
    command: start
  # This node receives updates but doesn't automatically generate them
  node1:
    container_name: currency-node1
    hostname: currency-node1
    image: github.com/hongkongkiwi/go-currency-nodes/node
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - "APP_NAME=node"
    ports:
      - 127.0.0.1:5051:5051
    expose:
      - 5051
    environment:
      - "NODE_LISTEN_ADDR=0.0.0.0:5051"
      - "NODE_ADVERTISE_ADDR=currency-node1:5051"
      - "NODE_CONTROLLER_ADDR=controller1:5060"
      - "NODE_UUID=b501cec4-36dd-4d7c-a1b9-5abc1d9290da"
      - "NODE_PAUSE_UPDATES=true"
      # Choose a selection of currency pairs
      - "NODE_CURRENCY_PAIRS=USD_HKD,HKD_USD,USD_NZD,NZD_USD"
      - "NODE_KEEPALIVE_INTERVAL=10s"
    command: start
    networks:
      - default
  # This node receives updates but doesn't automatically generate them
  node2:
    container_name: currency-node2
    hostname: currency-node2
    image: github.com/hongkongkiwi/go-currency-nodes/node
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - "APP_NAME=node"
    ports:
      - 127.0.0.1:5052:5052
    expose:
      - 5052
    environment:
      - "NODE_LISTEN_ADDR=0.0.0.0:5052"
      - "NODE_ADVERTISE_ADDR=currency-node1:5052"
      - "NODE_CONTROLLER_ADDR=controller1:5060"
      - "NODE_UUID=58f1f65e-b536-4be0-89ea-894a57f7e2bf"
      - "NODE_PAUSE_UPDATES=true"
      # Choose a selection of currency pairs
      - "NODE_CURRENCY_PAIRS=USD_NZD,NZD_USD,BTC_HKD,HKD_BTC,BTC_USD,USD_BTC"
      - "NODE_KEEPALIVE_INTERVAL=10s"
    command: start
  # This node transmits updates automatically
  node3:
    container_name: currency-node3
    hostname: currency-node3
    image: github.com/hongkongkiwi/go-currency-nodes/node
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - "APP_NAME=node"
    ports:
      - 127.0.0.1:5053:5053
    expose:
      - 5053
    environment:
      - "NODE_LISTEN_ADDR=0.0.0.0:5053"
      - "NODE_ADVERTISE_ADDR=currency-node1:5053"
      - "NODE_CONTROLLER_ADDR=controller1:5060"
      - "NODE_UUID=1ed2ebd8-6fc9-46f7-a156-6b9d9bff4982"
      # This node is going to spew updates
      - "NODE_PAUSE_UPDATES=false"
      # Generate an update minimum every 1s
      - "NODE_PRICEUPDATES_MIN_FREQ=1s"
      # Generate an update maximum every 5s
      - "NODE_PRICEUPDATES_MAX_FREQ=5s"
      # Change prices automatically 20% of old prices
      - "NODE_PRICEUPDATES_PERCENT=20"
      # Choose a selection of currency pairs (this node streams updates on these pairs)
      - "NODE_CURRENCY_PAIRS=USD_HKD,HKD_USD,USD_NZD,NZD_USD,BTC_HKD,HKD_BTC,BTC_USD,USD_BTC"
      - "NODE_KEEPALIVE_INTERVAL=10s"
    command: start
